### ISSUE TITLE
Crash when the installation is missing "account"

### ISSUE THREAD

**Issue by mikz** [probot/pino#28]
https://github.com/probot/pino/blob/0d0527c819c5287e95ca136209b4ce5611d4610d/index.js#L75 crashes.

The webhook probot gets contains:

```json
},
  "installation": {
    "id": 12276402,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTIyNzY0MDI="
  }
```

So it has no information about account or user. Honestly, I don't know why. But probot works, my integration worked since 2018. Would be great if error reporting would not crash.

**Comment by gr2m** [comment]
can you share the full event payload? I'd like to understand what the event/action is where the `account` property is empty. For the time being, can you send a PR to address the case, to prevent the crashes?

**Comment by mikz** [comment]
Sure I can, but it is not going to be much helpful. None of my events have `account` property. The app is subscribed only to Pull Request events. So this happens with synchronize, labeled, unlabeled, opened, reopened...

Yep, will send a PR.

**Comment by mikz** [comment]
Maybe because the app is installed not to the whole organization, but only to some repositories?
